// apps/frontend/admin-dashboard/src/components/common/SummaryCard.vue
<script setup>
defineProps({ item: { type: Object, required: true } });
</script>

<template>
  <article class="summary-card compact">
    <p>{{ item.title }}</p>
    <strong>{{ Number(item.value).toLocaleString() }}</strong>
    <span :class="Number(item.delta) < 0 ? 'down' : 'up'">{{ item.delta }} 전일 대비</span>
  </article>
</template>

// apps/frontend/admin-dashboard/src/components/SummaryCard.jsx
export function SummaryCard({ card }) {
  const Icon = card.icon;

  return (
    <article className="summary-card">
      <div className="summary-icon"><Icon size={20} /></div>
      <div>
        <p>{card.title}</p>
        <strong>{card.value.toLocaleString()}</strong>
        <span className={card.trend}>{card.delta} 전일 대비</span>
      </div>
    </article>
  );
}
